# Note: don't use this config for your own repositories. Instead, see
# "Version control integration" in README.md.
exclude: ^(fixtures/)
repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: black
      types: [python]
    - id: flake8
      name: flake8
      language: system
      entry: flake8
      types: [python]
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types: [python]
      exclude: tests/
